// Code generated by cspgen; DO NOT EDIT.
package csp

var ScriptHashes = []string{"sha256-+xqhQwI5T9dPH/l6xFZd6GNJ04llJksqJOyUBhgOEGQ=", "sha256-XDN9BzX9ZwDlVJam9ojBwGd++azP3+N2g6ty8VeH69Q="}

// Header is the Content-Security-Policy header for the dashboard build.
var Header = "default-src 'self'; script-src 'self' 'sha256-+xqhQwI5T9dPH/l6xFZd6GNJ04llJksqJOyUBhgOEGQ=' 'sha256-XDN9BzX9ZwDlVJam9ojBwGd++azP3+N2g6ty8VeH69Q='; style-src 'self' 'unsafe-inline'; font-src 'self'; worker-src 'self'; img-src 'self' blob: data:; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'"
